name = "stripe-worker"
main = "src/index.js"
account_id = "48c7b907c2e53e104dd054dbe13521c8"
compatibility_date = "2024-08-30"

[env.production]
vars = { STRIPE_SECRET_KEY = "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" }
